version: "3.9"
services:
  db:
    image: postgres:15
    container_name: bank_db
    restart: always
    environment:
      POSTGRES_DB: bank_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 5784
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  app:
    build: .
    container_name: bank_app
    restart: always
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/bank_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 5784
      SPRING_JPA_HIBERNATE_DDL_AUTO: none
      SPRING_LIQUIBASE_ENABLED: "true"
      JWT_SECRET: 98sd7g0s98g-df0h9gf9fgg7s98f6a8f7a6sf
      AES_KEY: A1B2C3D4E5F67890A1B4C7D2E5F97810
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
volumes:
  db_data:
