# application.yml — главный конфигурационный файл Spring Boot.
#Что нужно сделать:
#  - Указать настройки подключения к базе данных.
#  - Указать порт приложения.
#  - Настроить параметры безопасности и JWT.
#  - Включить Swagger UI.
server:
  port: 8080
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/bank_db
    username: postgres
    password: 5784
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none #validate format_sql: true
    open-in-view: false
security:
  jwt:
    secret: 98sd7g0s98g-df0h9gf9fgg7s98f6a8f7a6sf
    expiration-ms: 3600000

encryption:
  aes-key: A1B2C3D4E5F67890A1B4C7D2E5F97810

#liquibase:
#  change-log: classpath:db/changelog/db.changelog-master.xml